# PyTorch


## Set Up

In [1]:
import numpy as np
import torch

In [2]:
SEED = 13

In [3]:
np.random.seed(SEED)
torch.manual_seed(SEED)

## Basics

In [4]:
x = torch.randn(2, 3) # 2x3 tensor with elements sampled from standard normal distribution
print(f"Type: {x.type()}")
print(f"Shape: {x.shape}") # x.shape[0] = 2, x.shape[1] = 3
print(f"Size: {x.size()}") # x.size(0) = 2, x.size(1) = 3
print(f"Values: \n{x}")


Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Size: torch.Size([2, 3])
Values: 
tensor([[-0.1117, -1.1456,  1.4103],
        [ 1.3654,  1.1206, -0.9622]])


In [5]:
x = torch.zeros(2, 3)
print(x)
x = torch.ones(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [7]:
x = torch.Tensor(3, 4)
print(f"Size: {x.shape}")
print(f"Type: {x.type()}")
print(f"Values: \n{x}")

x = x.long()
print(f"Type: {x.type()}")
print(f"Values: \n{x}")

Size: torch.Size([3, 4])
Type: torch.FloatTensor
Values: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Type: torch.LongTensor
Values: 
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


## Operations

In [8]:
# Addition
x = torch.randn(3, 5)
y = torch.randn(3, 5)
z = x + y
print(f"Size: {z.shape}")
print(f"Values: \n{z}")


Size: torch.Size([3, 5])
Values: 
tensor([[-1.1098,  1.7537,  2.4030, -0.2083,  0.7284],
        [ 0.2871, -0.4396,  1.1117, -3.1672, -0.6673],
        [ 0.8865, -3.7948,  0.9182,  2.0378, -0.1944]])


In [9]:
# Dot product
x = torch.randn(3, 5)
y = torch.randn(5, 3)
z = torch.mm(x, y)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([3, 3])
Values: 
tensor([[-1.6036, -0.9863, -0.7855],
        [ 3.3653, -1.2471, -1.9053],
        [-1.6671,  0.2078,  0.2509]])


In [10]:
# Transpose
x = torch.randn(3, 5)
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

y = torch.t(x)
print(f"Size: {y.shape}")
print(F"Values: \n{y}")


Size: torch.Size([3, 5])
Values: 
tensor([[ 0.3487, -0.6250,  0.7299,  1.0591,  1.4792],
        [ 0.3538, -0.0571,  0.9229,  1.5556,  0.5269],
        [-0.0355,  0.4734, -1.5904,  1.5382,  0.5864]])
Size: torch.Size([5, 3])
Values: 
tensor([[ 0.3487,  0.3538, -0.0355],
        [-0.6250, -0.0571,  0.4734],
        [ 0.7299,  0.9229, -1.5904],
        [ 1.0591,  1.5556,  1.5382],
        [ 1.4792,  0.5269,  0.5864]])


In [11]:
# Reshape
x = torch.randn(3, 5)
z = x.view(5, 3) # view() is similar to numpy's reshape()
print(f"Size: {z.shape}")
print(f"Values: \n{z}")


Size: torch.Size([5, 3])
Values: 
tensor([[-0.4355,  1.1272,  0.8872],
        [ 2.0036, -0.6989,  0.3956],
        [ 1.9219,  2.0461, -0.8952],
        [-1.3377, -1.9918,  1.0226],
        [-1.2937, -0.8858,  2.0733]])


In [12]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [13]:
# Dimensional Operations

x = torch.randn(2, 3, 5)
print(f"Values: \n{x}")

y = torch.sum(x, dim=0)
print(f"Values: \n{y}")
print(f"Shape: {y.shape}")

z = torch.sum(x, dim=1)
print(f"Values: \n{z}")
print(f"Shape: {z.shape}")

Values: 
tensor([[[-1.6802, -0.2643, -2.4211, -0.4847,  0.8751],
         [-0.3173,  0.9739,  1.2828,  1.9910,  1.2427],
         [-0.8392, -0.3355,  0.6086, -2.8491, -0.2504]],

        [[ 0.1026,  1.2805,  1.2924,  0.1837,  0.8709],
         [-1.2112,  1.7930, -0.3857, -0.2274,  1.2998],
         [ 0.4570,  1.2515, -1.3627, -0.3052, -0.2291]]])
Values: 
tensor([[-1.5776,  1.0162, -1.1286, -0.3011,  1.7461],
        [-1.5286,  2.7669,  0.8971,  1.7636,  2.5425],
        [-0.3822,  0.9159, -0.7541, -3.1543, -0.4794]])
Shape: torch.Size([3, 5])
Values: 
tensor([[-2.8368,  0.3740, -0.5296, -1.3429,  1.8675],
        [-0.6516,  4.3250, -0.4559, -0.3489,  1.9417]])
Shape: torch.Size([2, 5])


## Indexing, Splicing and Joining

In [14]:
# Indexing
x = torch.randn(3, 4)
print (f"x: \n{x}")
print (f"x[:1]: \n{x[:1]}")
print (f"x[:1, 1:3]: \n{x[:1, 1:3]}")

x: 
tensor([[ 0.2695, -0.2611, -0.2189,  0.6673],
        [ 0.1421, -0.2254, -0.8187,  0.3086],
        [-0.1409,  1.3298, -0.9942, -0.1846]])
x[:1]: 
tensor([[ 0.2695, -0.2611, -0.2189,  0.6673]])
x[:1, 1:3]: 
tensor([[-0.2611, -0.2189]])


In [15]:
# Splicing
x = torch.randn(2, 3)
print(f"Values: \n{x}")

col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index = col_indices)
print(f"Values: \n{chosen}")

row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices]
print(f"Values: \n{chosen}")

Values: 
tensor([[-1.5813,  2.0656,  0.0815],
        [-0.7569,  0.2151,  0.9604]])
Values: 
tensor([[-1.5813,  0.0815],
        [-0.7569,  0.9604]])
Values: 
tensor([-1.5813,  0.9604])


In [16]:
# Joining & Concatenation
x = torch.randn(3, 5)
print(f"Values: \n{x}")
y = torch.cat([x, x], dim=0)
print(f"Values: \n{y}")
print(f"Size: {y.shape}")

Values: 
tensor([[ 0.9429,  0.0541, -0.8245,  0.9775, -0.2061],
        [-0.0520, -0.7840, -0.7747, -0.9179,  0.4904],
        [ 2.2701, -2.1641,  1.8631,  0.0698, -0.2198]])
Values: 
tensor([[ 0.9429,  0.0541, -0.8245,  0.9775, -0.2061],
        [-0.0520, -0.7840, -0.7747, -0.9179,  0.4904],
        [ 2.2701, -2.1641,  1.8631,  0.0698, -0.2198],
        [ 0.9429,  0.0541, -0.8245,  0.9775, -0.2061],
        [-0.0520, -0.7840, -0.7747, -0.9179,  0.4904],
        [ 2.2701, -2.1641,  1.8631,  0.0698, -0.2198]])
Size: torch.Size([6, 5])


## Gradients

$y = 3x + 2$

$z = \sum y / N$

$\frac{\partial z}{\partial x} = \frac{\partial z}{\partial y} \frac{\partial y}{\partial x} = \frac{1}{N} \times 3 = \frac{1}{12} \times 3 = \frac{1}{4}$

In [17]:
x = torch.rand(3, 4, requires_grad=True)
y = 3 * x + 2
z = y.mean()
z.backward()
print(f"x: \n{x}")
print(f"x.grad: \n{x.grad}")

x: 
tensor([[0.0104, 0.1743, 0.7130, 0.5399],
        [0.0688, 0.4628, 0.7397, 0.0760],
        [0.1594, 0.9080, 0.3168, 0.2054]], requires_grad=True)
x.grad: 
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


## CUDA

In [18]:
print(torch.cuda.is_available())

False


In [19]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [20]:
x = torch.randn(3, 5)
print(x.is_cuda)


False


In [21]:
x = torch.randn(3, 5).to(device)
print(x.is_cuda)

False
