# PyTorch


## Set Up

In [1]:
import numpy as np
import torch

In [2]:
SEED = 13

In [3]:
np.random.seed(SEED)
torch.manual_seed(SEED)

## Basics

In [8]:
x = torch.randn(2, 3) # 2x3 tensor with elements sampled from standard normal distribution
print(f"Type: {x.type()}")
print(f"Shape: {x.shape}") # x.shape[0] = 2, x.shape[1] = 3
print(f"Size: {x.size()}") # x.size(0) = 2, x.size(1) = 3
print(f"Values: \n{x}")


Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Size: torch.Size([2, 3])
2
Values: 
tensor([[-0.4406,  0.7069,  0.9999],
        [-0.8294,  1.7844, -2.4621]])


In [9]:
x = torch.zeros(2, 3)
print(x)
x = torch.ones(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [11]:
x = torch.Tensor(3, 4)
print(f"Size: {x.shape}")
print(f"Type: {x.type()}")
print(f"Values: \n{x}")

x = x.long()
print(f"Type: {x.type()}")
print(f"Values: \n{x}")

Size: torch.Size([3, 4])
Type: torch.FloatTensor
Values: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Type: torch.LongTensor
Values: 
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


## Operations

In [12]:
# Addition
x = torch.randn(3, 5)
y = torch.randn(3, 5)
z = x + y
print(f"Size: {z.shape}")
print(f"Values: \n{z}")


Size: torch.Size([3, 5])
Values: 
tensor([[ 0.3233, -0.0436, -2.6316,  1.4815, -0.3328],
        [ 1.3547,  2.9480, -0.3390, -1.3738,  0.2870],
        [-1.3033, -1.0380,  1.2862,  1.3678, -0.1132]])


In [13]:
# Dot product
x = torch.randn(3, 5)
y = torch.randn(5, 3)
z = torch.mm(x, y)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([3, 3])
Values: 
tensor([[ 0.9100, -0.3729,  0.8425],
        [ 3.1695,  1.4920, -1.0507],
        [ 5.0806,  2.9653, -0.1704]])


In [14]:
# Transpose
x = torch.randn(3, 5)
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

y = torch.t(x)
print(f"Size: {y.shape}")
print(F"Values: \n{y}")


Size: torch.Size([3, 5])
Values: 
tensor([[-1.3377, -1.9918,  1.0226, -1.2937, -0.8858],
        [ 2.0733, -0.1818, -1.5408, -1.7559,  0.3658],
        [ 0.8208, -0.6577,  0.1664, -1.1094,  0.5930]])
Size: torch.Size([5, 3])
Values: 
tensor([[-1.3377,  2.0733,  0.8208],
        [-1.9918, -0.1818, -0.6577],
        [ 1.0226, -1.5408,  0.1664],
        [-1.2937, -1.7559, -1.1094],
        [-0.8858,  0.3658,  0.5930]])


In [15]:
# Reshape
x = torch.randn(3, 5)
z = x.view(5, 3) # view() is similar to numpy's reshape()
print(f"Size: {z.shape}")
print(f"Values: \n{z}")


Size: torch.Size([5, 3])
Values: 
tensor([[-0.2506,  0.6856, -0.6429],
        [ 1.0606, -0.2093,  1.7014],
        [-0.5920, -1.0155,  0.0900],
        [-0.3933,  0.6828,  1.8321],
        [ 0.1098, -0.8053,  1.8844]])


In [17]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [18]:
# Dimensional Operations

x = torch.randn(2, 3, 5)
print(f"Values: \n{x}")

y = torch.sum(x, dim=0)
print(f"Values: \n{y}")
print(f"Shape: {y.shape}")

z = torch.sum(x, dim=1)
print(f"Values: \n{z}")
print(f"Shape: {z.shape}")

Values: 
tensor([[[-1.0289, -0.5078, -0.4231, -0.4975,  1.4085],
         [-0.1853, -1.3571,  0.2369,  0.9741, -1.7030],
         [ 1.1677, -1.7351,  0.3593, -0.1591,  0.8326]],

        [[-1.1986,  0.3564,  1.3168,  0.4175, -1.5278],
         [-0.8360, -0.6593,  1.5188,  0.6603,  0.9863],
         [ 0.9969,  1.1030, -0.0773, -0.0147,  0.8177]]])
Values: 
tensor([[-2.2275, -0.1514,  0.8937, -0.0800, -0.1193],
        [-1.0212, -2.0164,  1.7557,  1.6343, -0.7167],
        [ 2.1646, -0.6322,  0.2819, -0.1737,  1.6503]])
Shape: torch.Size([3, 5])
Values: 
tensor([[-0.0465, -3.6001,  0.1731,  0.3175,  0.5381],
        [-1.0376,  0.8001,  2.7583,  1.0631,  0.2761]])
Shape: torch.Size([2, 5])


## Indexing, Splicing and Joining

In [19]:
# Indexing
x = torch.randn(3, 4)
print (f"x: \n{x}")
print (f"x[:1]: \n{x[:1]}")
print (f"x[:1, 1:3]: \n{x[:1, 1:3]}")

x: 
tensor([[-0.7840, -0.7747, -0.9179,  0.4904],
        [ 2.2701, -2.1641,  1.8631,  0.0698],
        [-0.2198,  1.7412,  1.3517,  0.7791]])
x[:1]: 
tensor([[-0.7840, -0.7747, -0.9179,  0.4904]])
x[:1, 1:3]: 
tensor([[-0.7747, -0.9179]])


In [20]:
# Splicing
x = torch.randn(2, 3)
print(f"Values: \n{x}")

col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index = col_indices)
print(f"Values: \n{chosen}")

row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices]
print(f"Values: \n{chosen}")

Values: 
tensor([[-2.1216, -0.6979, -0.1950],
        [ 1.2209, -0.7639, -0.5570]])
Values: 
tensor([[-2.1216, -0.1950],
        [ 1.2209, -0.5570]])
Values: 
tensor([-2.1216, -0.5570])


In [22]:
# Joining & Concatenation
x = torch.randn(3, 5)
print(f"Values: \n{x}")
y = torch.cat([x, x], dim=0)
print(f"Values: \n{y}")
print(f"Size: {y.shape}")

Values: 
tensor([[-0.1667,  2.2473,  0.8457, -0.6124, -0.5656],
        [ 0.0434, -0.4750, -2.4320, -0.7770,  0.2803],
        [ 0.9992, -0.3607,  1.3189, -0.4596,  0.1660]])
Values: 
tensor([[-0.1667,  2.2473,  0.8457, -0.6124, -0.5656],
        [ 0.0434, -0.4750, -2.4320, -0.7770,  0.2803],
        [ 0.9992, -0.3607,  1.3189, -0.4596,  0.1660],
        [-0.1667,  2.2473,  0.8457, -0.6124, -0.5656],
        [ 0.0434, -0.4750, -2.4320, -0.7770,  0.2803],
        [ 0.9992, -0.3607,  1.3189, -0.4596,  0.1660]])
Size: torch.Size([6, 5])


## Gradients

$y = 3x + 2$

$z = \sum y / N$

$\frac{\partial z}{\partial x} = \frac{\partial z}{\partial y} \frac{\partial y}{\partial x} = \frac{1}{N} \times 3 = \frac{1}{12} \times 3 = \frac{1}{4}$

In [23]:
x = torch.rand(3, 4, requires_grad=True)
y = 3 * x + 2
z = y.mean()
z.backward()
print(f"x: \n{x}")
print(f"x.grad: \n{x.grad}")

x: 
tensor([[0.3776, 0.5684, 0.9340, 0.2461],
        [0.6760, 0.4133, 0.7686, 0.8189],
        [0.4689, 0.7358, 0.4311, 0.5170]], requires_grad=True)
x.grad: 
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


## CUDA

In [24]:
print(torch.cuda.is_available())

False


In [25]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [26]:
x = torch.randn(3, 5)
print(x.is_cuda)


False


In [27]:
x = torch.randn(3, 5).to(device)
print(x.is_cuda)

False
